services:
  builder:
    image: mirisbowring/texlive_ctan_full:2019
    # build:
    #   context: .
    user: ${MY_UID}:${MY_GID}
    volumes:
    - ../../:/build
    - ../tmp/data/:/data/
    - ../tmp/temp/:/temp/
